### ISSUE TITLE
Better `happy.svg` NFT

### ISSUE THREAD

**Issue by preslavxyz** [Cyfrin/foundry-nft-cu#37]
I would recommend you replacing your smily face with mine because the eye is fixed.

```svg
<svg viewBox="0 0 200 200" width="400"  height="400" xmlns="http://www.w3.org/2000/svg">
  <circle cx="100" cy="100" fill="yellow" r="78" stroke="black" stroke-width="3"/>
  <g class="eyes">
    <circle cx="70" cy="82" r="12"/>
    <circle cx="127" cy="82" r="12"/>
  </g>
  <path d="m136.81 116.53c.69 26.17-64.11 42-81.52-.73" style="fill:none; stroke: black; stroke-width: 3;"/>
</svg>
```

**Comment by preslavxyz** [comment]
data:image/svg+xml;base64,PHN2ZyB2aWV3Qm94PSIwIDAgMjAwIDIwMCIgd2lkdGg9IjQwMCIgIGhlaWdodD0iNDAwIiB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciPgogIDxjaXJjbGUgY3g9IjEwMCIgY3k9IjEwMCIgZmlsbD0ieWVsbG93IiByPSI3OCIgc3Ryb2tlPSJibGFjayIgc3Ryb2tlLXdpZHRoPSIzIi8+CiAgPGcgY2xhc3M9ImV5ZXMiPgogICAgPGNpcmNsZSBjeD0iNzAiIGN5PSI4MiIgcj0iMTIiLz4KICAgIDxjaXJjbGUgY3g9IjEyNyIgY3k9IjgyIiByPSIxMiIvPgogIDwvZz4KICA8cGF0aCBkPSJtMTM2LjgxIDExNi41M2MuNjkgMjYuMTctNjQuMTEgNDItODEuNTItLjczIiBzdHlsZT0iZmlsbDpub25lOyBzdHJva2U6IGJsYWNrOyBzdHJva2Utd2lkdGg6IDM7Ii8+Cjwvc3ZnPg==

**Comment by PatrickAlphaC** [comment]
ahahahahahha. 

Yes, please make a PR if you'd like!
