### ISSUE TITLE
MakeFile issue

### ISSUE THREAD

**Issue by nitinaimshigh** [Cyfrin/foundry-nft-cu#39]
When i enter the **make deploy** in command line, i get this error. It's for every make command. Please help. TIA.
make: *** No rule to make target 'deploy'.  Stop.

**Comment by cromewar** [comment]
Hello @nitinaimshigh 
The makefile requires you to specify the network you are deploying to:

```toml
deploy:
	@forge script script/DeployBasicNft.s.sol:DeployBasicNft $(NETWORK_ARGS)
```

Are you sending over the correct network?

**Comment by nitinaimshigh** [comment]
Hi Vasiliy,
Thanks for the reply. The issue was, I had misspelled the file as MakeFile
instead of Makefile. So it got resolved as soon as the change was made.
Thanks again.
Nitin
